<?php

use PHPUnit\Framework\TestCase;
use Circlical\Subtitles\Subtitles;

class PublicInterfaceTest extends TestCase
{

    use AdditionalAssertions;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testLoadFromString()
    {
        $string = "
1
00:02:17,440 --> 00:02:20,375
Senator, we're making
our final approach into Coruscant.
    ";
        $subtitles = Subtitles::load($string, 'srt');

        $this->assertTrue(!empty($subtitles->getInternalFormat()));
    }

    public function testContent()
    {
        $content = Subtitles::load(file_get_contents('./tests/files/srt_for_public_interface_test.srt'), 'srt')->content('srt');
        $this->assertTrue(strlen($content) > 10); // 10 - just random number
    }

    public function testNonExistentFormatThrowsError()
    {
        $this->expectException(Exception::class);
        Subtitles::load(file_get_contents('./tests/files/srt_for_public_interface_test.srt'), 'srt')->content('exe');
    }

    public function testAdd()
    {
        $subtitles = new Subtitles();
        $subtitles->add(1, 2, 'Hello World');
        $generatedFormat = $subtitles->getInternalFormat();
        $expectedFormat = [
            [
                'start' => 1.0,
                'end' => 2.0,
                'lines' => ['Hello World'],
            ],
        ];

        $this->assertTrue($expectedFormat === $generatedFormat);
    }

    public function testAddOrdersSubtitlesByTime()
    {
        $expectedFormat = [
            [
                'start' => 0.0,
                'end' => 5.0,
                'lines' => ['text 1'],
            ],
            [
                'start' => 10.0,
                'end' => 15.0,
                'lines' => ['text 2'],
            ],
        ];

        $subtitles = new Subtitles();
        $subtitles->add(10, 15, 'text 2');
        $subtitles->add(0, 5, 'text 1');
        $generatedFormat = $subtitles->getInternalFormat();

        $this->assertInternalFormatsEqual($expectedFormat, $generatedFormat);
    }

    // ----------------------------------------- remove() --------------------------------------------------------------
    public function testRemove()
    {
        $actual_internal_format = (new Subtitles())
            ->add(1, 3, 'Hello World')
            ->remove(0, 2)
            ->getInternalFormat();

        $this->assertTrue(empty($actual_internal_format));
    }

    public function testRemoveDoesNotRemoveIfTimesDoNotOverlapAtTheBeginning()
    {
        $actual_internal_format = (new Subtitles())
            ->add(1, 3, 'Hello World')
            ->remove(0, 1)
            ->getInternalFormat();

        $this->assertTrue(!empty($actual_internal_format));
    }

    public function testRemoveDoesNotRemoveIfTimesDoNotOverlapAtTheEnd()
    {
        $actual_internal_format = (new Subtitles())
            ->add(1, 3, 'Hello World')
            ->remove(3, 4)
            ->getInternalFormat();

        $this->assertTrue(!empty($actual_internal_format));
    }

    // ------------------------------------------------ time() ---------------------------------------------------------
    public function testAddTime()
    {
        $generatedFormat = (new Subtitles())
            ->add(1, 3, 'Hello World')
            ->shiftTime(1.0)
            ->getInternalFormat();

        $expectedFormat = [
            [
                'start' => 2.0,
                'end' => 4.0,
                'lines' => ['Hello World'],
            ],
        ];

        $this->assertTrue($expectedFormat === $generatedFormat);
    }

    public function testSubtractTime()
    {
        $generatedFormat = (new Subtitles())
            ->add(1, 3, 'Hello World')
            ->shiftTime(-1)
            ->getInternalFormat();

        $expectedFormat = [
            [
                'start' => 0.0,
                'end' => 2.0,
                'lines' => ['Hello World'],
            ],
        ];

        $this->assertTrue($expectedFormat === $generatedFormat);
    }

    public function testFromTillTime()
    {
        $generatedFormat = (new Subtitles())
            ->add(1, 3, 'a')
            ->shiftTime(1, 1, 3)
            ->getInternalFormat();

        $expectedFormat = [
            [
                'start' => 2.0,
                'end' => 4.0,
                'lines' => ['a'],
            ],
        ];

        $this->assertTrue($expectedFormat === $generatedFormat);
    }

    public function testFromTillTimeWhenNotInRange()
    {
        $generatedFormat1 = (new Subtitles())
            ->add(1, 3, 'a')
            ->shiftTime(1, 0, 0.5)
            ->getInternalFormat();

        $generatedFormat2 = (new Subtitles())
            ->add(1, 3, 'a')
            ->shiftTime(1, 4, 5)
            ->getInternalFormat();

        $expectedFormat = [
            [
                'start' => 1.0,
                'end' => 3.0,
                'lines' => ['a'],
            ],
        ];

        $this->assertTrue($expectedFormat === $generatedFormat1);
        $this->assertTrue($expectedFormat === $generatedFormat2);
    }

    public function testFromTillTimeOverlappingStart()
    {
        $generatedFormat = (new Subtitles())
            ->add(1, 3, 'a')
            ->shiftTime(1, 0, 1)
            ->getInternalFormat();

        $expectedFormat = [
            [
                'start' => 2.0,
                'end' => 4.0,
                'lines' => ['a'],
            ],
        ];

        $this->assertTrue($expectedFormat === $generatedFormat);
    }

    public function testSiftTimeGradually()
    {
        $actual_internal_format = (new Subtitles())
            ->add(0, 2, 'a')
            ->add(2, 4, 'a')
            ->add(4, 6, 'a')
            ->shiftTimeGradually(3)
            ->getInternalFormat();
        $expected_internal_format = (new Subtitles())
            ->add(0, 3, 'a')
            ->add(3, 6, 'a')
            ->add(6, 9, 'a')
            ->getInternalFormat();

        $this->assertInternalFormatsEqual($expected_internal_format, $actual_internal_format);
    }

    public function testSiftTimeGraduallyWithFromAndTill()
    {
        $actual_internal_format = (new Subtitles())
            ->add(0, 2, 'a')
            ->add(2, 4, 'a')
            ->add(4, 6, 'a')
            ->add(6, 8, 'a')
            ->add(8, 10, 'a')
            ->shiftTimeGradually(3, 2, 8)
            ->getInternalFormat();
        $expected_internal_format = (new Subtitles())
            ->add(0, 2, 'a')
            ->add(2, 5, 'a')
            ->add(5, 8, 'a')
            ->add(8, 11, 'a')
            ->add(8, 10, 'a')
            ->getInternalFormat();

        $this->assertInternalFormatsEqual($expected_internal_format, $actual_internal_format);
    }
}